# Aider should co-author-by because I'm the center of the universe
attribute-co-authored-by: true
watch-files: true
vim: true
notifications: true
model: openrouter/google/gemini-2.5-pro
weak-model: openrouter/google/gemini-2.5-flash
alias:
  - "gemini:openrouter/google/gemini-2.5-pro"
