#!/bin/sh
mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm .git/tags.$$" EXIT

ctags --tag-relative -R -f .git/tags.$$ --languages=-javascript,-css,-markdown
mv .git/tags.$$ .git/tags
