name: Docker Build + Push
on:
  push:
    branches:
      - master

  # Build daily at 4am UTC
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: eligundry
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build --pull -t eligundry/dots .
      - run: docker push eligundry/dots
